// Mackerel-030F Top Level SoC Module — ULX3S (Lattice ECP5-85F)
//
// First bring-up cut only (plan.md step 3/8): on-chip ROM + a single GPIO
// (LED) register. No SDRAM/UART/SPI/interrupts yet — those are separate,
// later increments per plan.md's own staged bring-up order, deliberately
// not all attempted at once.
//
// Drops m68030_top (cores/mh030/rtl/m68030_top.sv) in place of Mackerel-F's
// own fx68k, onto its real, pin-accurate MC68030 bus: 32-bit data, single
// /DS, SIZ[1:0]+DSACK0/1 dynamic bus sizing (not fixed-width DTACK), /AVEC
// (not /VPA). See plan.md's "Reference: what Mackerel-F actually is"
// section for the full comparison this module's shape is based on.
`default_nettype none

module mackerel_030f (
    input  wire clk_25mhz,   // board oscillator, pin G2

    output wire [7:0] led,   // 8 onboard LEDs

    input  wire [6:0] btn,   // onboard buttons (unused this cut)

    // FTDI USB-UART: not wired up yet (next bring-up increment). Declared
    // now so the pin constraints are already correct and stable; tied to
    // an idle mark so nothing floats.
    output wire ftdi_rxd,    // FPGA -> FTDI (this is the FPGA's UART TX)
    input  wire ftdi_txd     // FTDI -> FPGA (this is the FPGA's UART RX)
);

    assign ftdi_rxd = 1'b1;  // UART idle-mark; real UART is a later increment

    // ─── Clock: 25 MHz board osc -> 100 MHz clk_4x (25 MHz external bus) ───
    // Generated by Project Trellis's own `ecppll -i 25 -o 100`, not hand-
    // derived EHXPLLL parameters (see clk_pll.v).
    wire clk_4x, pll_locked;
    clk_pll u_pll (
        .clkin   (clk_25mhz),
        .clkout0 (clk_4x),
        .locked  (pll_locked)
    );

    // ─── Power-on reset: hold rst_n low until the PLL locks, then a further
    // fixed count for margin (mirrors Mackerel-F's own rst_cpu counter
    // shape; m68030_top's own biu_config.sv handles the real internal
    // reset SEQUENCING once rst_n releases — see MH030's CLAUDE.md).
    reg [15:0] rst_ctr_r = 16'h0;
    wire rst_n = rst_ctr_r[15];
    always @(posedge clk_4x or negedge pll_locked) begin
        if (!pll_locked)
            rst_ctr_r <= 16'h0;
        else if (!rst_n)
            rst_ctr_r <= rst_ctr_r + 16'h1;
    end

    // ─── m68030_top external pins ───────────────────────────────────────
    wire [31:0] ext_a;
    wire [31:0] ext_d_out;
    wire        ext_d_oe;
    wire [31:0] ext_d_in;
    wire        ext_as_n, ext_ds_n, ext_rw;
    wire [2:0]  ext_fc;
    wire [1:0]  ext_siz;
    wire        ext_ecs_n, ext_ocs_n, ext_rstout_n, ext_cbreq_n, ext_bg_n;
    wire        ext_rmc_n, ext_dben_n, ext_ipend_n;
    wire        bus_halted, eu_stop, eu_addr_err, ifu_addr_err;
    wire        status_n, ciout_n;

    // This glue's own responses, driven into m68030_top's input ports.
    wire dsack0_n, dsack1_n, berr_n;

    m68030_top u_cpu (
        .clk_4x        (clk_4x),
        .rst_n         (rst_n),

        .ext_a         (ext_a),
        .ext_d_out     (ext_d_out),
        .ext_d_oe      (ext_d_oe),
        .ext_d_in      (ext_d_in),
        .ext_as_n      (ext_as_n),
        .ext_ds_n      (ext_ds_n),
        .ext_rw        (ext_rw),
        .ext_fc        (ext_fc),
        .ext_siz       (ext_siz),
        .ext_ecs_n     (ext_ecs_n),
        .ext_ocs_n     (ext_ocs_n),
        .ext_rstout_n  (ext_rstout_n),
        .ext_cbreq_n   (ext_cbreq_n),
        .ext_bg_n      (ext_bg_n),
        .ext_rmc_n     (ext_rmc_n),
        .ext_dben_n    (ext_dben_n),
        .ext_ipend_n   (ext_ipend_n),
        .bus_halted    (bus_halted),
        .eu_stop       (eu_stop),
        .eu_addr_err   (eu_addr_err),
        .ifu_addr_err  (ifu_addr_err),

        .dsack0_n      (dsack0_n),
        .dsack1_n      (dsack1_n),
        .sterm_n       (1'b1),        // no synchronous-termination peripheral yet
        .berr_n        (berr_n),
        .halt_n        (1'b1),        // no external HALT source
        .status_n      (status_n),
        .avec_n        (avec_n_w),
        .ipl_n         (3'b111),      // no interrupt sources wired yet
        .br_n          (1'b1),        // no external bus master (no DMA)
        .bgack_n       (1'b1),
        .cback_n       (1'b1),        // no burst-capable memory yet
        .ciin_n        (1'b1),        // cache-inhibit input unused (caches disabled at reset)
        .ciout_n       (ciout_n),
        .cdis_n        (1'b1),        // cache not emulator-disabled
        .mmudis_n      (1'b1)         // MMU not emulator-disabled
    );

    // ─── Autovectoring (plan.md step 7): swap 68000's VPAn for real 68030
    // /AVEC. Every CPU-space (IACK) cycle here autovectors, matching
    // Mackerel-F's own VPAn-tied-low approach — there's no real interrupt
    // controller yet (ipl_n is tied inactive above), so this only matters
    // once an interrupt source exists, but ties it correctly now rather
    // than leaving it undefined.
    wire cpu_space = (ext_fc == 3'b111);
    wire iack      = cpu_space && !ext_as_n;
    wire avec_n_w  = !iack;

    // ─── Memory map (first cut only) ────────────────────────────────────
    //   ROM   0x00000000-0x00000FFF   4 KB, on-chip, $readmemh
    //   GPIO  0xFFFFFF00               1 register (write: D[7:0] -> led)
    //   (else) unmapped -> BERR via watchdog
    //
    // Real data-phase gate: for a 68030 write cycle AS asserts at S1 but
    // DS doesn't assert until S3 (data isn't stable until then) -- unlike
    // a plain 68000, so responses are gated on /DS, not /AS, for both
    // reads and writes (reads assert AS+DS together anyway, so this is
    // equivalent there and strictly correct for writes). See MH030's
    // CLAUDE.md S-State Signal Timing section.
    wire cyc_active = !ext_ds_n;

    wire in_rom  = cyc_active && (ext_a[31:12] == 20'h00000);
    wire in_gpio = cyc_active && (ext_a == 32'hFFFFFF00);
    wire in_any  = in_rom || in_gpio;

    // 32-bit-port DSACK encoding, confirmed directly against MH030's own
    // rtl/biu_sizing_fsm.sv (next_siz/needs_more): dsack1_n=0,dsack0_n=0
    // (both asserted) decodes as port={dsack1_s,dsack0_s}=2'b11 -> 32-bit
    // port, whole request satisfied in one beat. Zero added wait states,
    // matching a real on-chip ROM/register (same shape as Mackerel-F's
    // own zero-wait-state ROM/GPIO, just with the real 68030 3-state
    // DSACK encoding instead of a single DTACK line).
    assign dsack0_n = !in_any;
    assign dsack1_n = !in_any;

    // ─── ROM: on-chip, longword-indexed. Registered (synchronous) read --
    // deliberately the real BRAM-inferable idiom (single indexed write-
    // never/read-every-cycle, registered output), not a combinational
    // array read, so this maps to a real ECP5 EBR block rather than
    // distributed LUT fabric.
    reg [31:0] rom [0:1023];
    reg [31:0] rom_dout_r;
    initial $readmemh("rom.hex", rom);
    always @(posedge clk_4x)
        rom_dout_r <= rom[ext_a[11:2]];

    // ─── GPIO: single write-only longword register -> 8 LEDs ───────────
    reg [7:0] led_r = 8'h00;
    always @(posedge clk_4x or negedge rst_n) begin
        if (!rst_n)
            led_r <= 8'h00;
        else if (in_gpio && !ext_rw)
            led_r <= ext_d_out[7:0];
    end
    assign led = led_r;

    // ─── Data bus input mux (CPU read side) ─────────────────────────────
    assign ext_d_in = in_rom ? rom_dout_r : 32'h00000000;

    // ─── Bus watchdog: BERR on any access to unmapped space. Mirrors
    // Mackerel-F's own bus_watchdog.v, adapted for DSACK-based
    // termination instead of DTACK. Threshold is generous (64 clk_4x
    // ticks, i.e. many bus cycles' worth) since there is no real timing
    // pressure to be tight here -- only unmapped accesses ever reach it.
    reg [6:0] wd_ctr_r;
    reg       berr_r;
    always @(posedge clk_4x or negedge rst_n) begin
        if (!rst_n) begin
            wd_ctr_r <= 7'h0;
            berr_r   <= 1'b0;
        end else if (ext_as_n) begin
            wd_ctr_r <= 7'h0;
            berr_r   <= 1'b0;
        end else if (in_any) begin
            wd_ctr_r <= 7'h0;
            berr_r   <= 1'b0;
        end else if (wd_ctr_r == 7'd64) begin
            berr_r   <= 1'b1;
        end else begin
            wd_ctr_r <= wd_ctr_r + 7'h1;
        end
    end
    assign berr_n = !berr_r;

endmodule
