// Mackerel-030F Top Level SoC Module — ULX3S (Lattice ECP5-85F)
//
// Bring-up cut 3 (plan.md step 3/8): on-chip ROM + GPIO (LED) register +
// UART console + real off-chip SDRAM. UART via the same OpenCores
// uart16550 core Mackerel-F itself uses (cores/uart16550, fetched by
// cores/get_cores.sh) behind its own proven wrapper (uart.v, adapted from
// Mackerel-F's pld/mackerel-f/uart.v essentially unchanged). SDRAM via
// vendor/sdram_16bit.v (EMARD's ULX3S-cleaned-up Next186 SoC controller)
// behind sdram_adapter.v -- see that file's own header for the real
// parameters (confirmed against ulx3s_v20.lpf's own pin list, not
// assumed) and the refresh-timing bug found and fixed in the vendored
// defaults. No SPI/interrupts yet — those are separate, later increments
// per plan.md's own staged bring-up order, deliberately not all
// attempted at once.
//
// Drops m68030_top (cores/mh030/rtl/m68030_top.sv) in place of Mackerel-F's
// own fx68k, onto its real, pin-accurate MC68030 bus: 32-bit data, single
// /DS, SIZ[1:0]+DSACK0/1 dynamic bus sizing (not fixed-width DTACK), /AVEC
// (not /VPA). See plan.md's "Reference: what Mackerel-F actually is"
// section for the full comparison this module's shape is based on.
`default_nettype none

module mackerel_030f (
    input  wire clk_25mhz,   // board oscillator, pin G2

    output wire [7:0] led,   // 8 onboard LEDs

    input  wire [6:0] btn,   // onboard buttons (unused this cut)

    // FTDI USB-UART. Per ulx3s_v20.lpf's own comments: "ftdi_rxd" is the
    // FPGA's OWN transmit pin (named for the FTDI chip's RXD input it
    // drives), "ftdi_txd" is the FPGA's OWN receive pin.
    output wire ftdi_rxd,    // FPGA -> FTDI (this is the FPGA's UART TX)
    input  wire ftdi_txd,    // FTDI -> FPGA (this is the FPGA's UART RX)

    // SDRAM (real off-chip MT48LC32M16-class part -- pins/widths confirmed
    // directly against ulx3s_v20.lpf, not assumed).
    output wire        sdram_clk,
    output wire        sdram_cke,
    output wire        sdram_csn,
    output wire        sdram_wen,
    output wire        sdram_rasn,
    output wire        sdram_casn,
    output wire [12:0] sdram_a,
    output wire [1:0]  sdram_ba,
    output wire [1:0]  sdram_dqm,
    inout  wire [15:0] sdram_d,

    // Onboard microSD slot, SPI mode -- pin names/roles confirmed
    // directly against ulx3s_v20.lpf's own comments (sd_cmd_di=MOSI,
    // sd_d0_do=MISO, sd_d3_csn=CS#). sd_d must be declared as the real
    // 4-bit array ulx3s_v20.lpf itself constrains ("sd_d[3]"/"sd_d[0]",
    // not separate scalar "sd_d3"/"sd_d0" ports -- nextpnr's own
    // "IO 'sd_d3' is unconstrained in LPF" error caught this mismatch
    // directly) -- only bits [3] (CS#, output) and [0] (MISO, input) are
    // ever driven/read below; [2:1] are deliberately left unconnected,
    // matching the .lpf's own note that doing so avoids a conflict with
    // the onboard ESP32's wifi_gpio4/12, which this project doesn't use.
    output wire sd_clk,
    output wire sd_cmd,
    inout  wire [3:0] sd_d
);

    // ─── Clock: 25 MHz board osc -> 100 MHz clk_4x (25 MHz external bus) ───
    // Generated by Project Trellis's own `ecppll -i 25 -o 100`, not hand-
    // derived EHXPLLL parameters (see clk_pll.v).
    wire clk_4x, pll_locked;
    clk_pll u_pll (
        .clkin   (clk_25mhz),
        .clkout0 (clk_4x),
        .locked  (pll_locked)
    );

    // ─── Power-on reset: hold rst_n low until the PLL locks, then a further
    // fixed count for margin (mirrors Mackerel-F's own rst_cpu counter
    // shape; m68030_top's own biu_config.sv handles the real internal
    // reset SEQUENCING once rst_n releases — see MH030's CLAUDE.md).
    reg [15:0] rst_ctr_r = 16'h0;
    wire rst_n = rst_ctr_r[15];
    always @(posedge clk_4x or negedge pll_locked) begin
        if (!pll_locked)
            rst_ctr_r <= 16'h0;
        else if (!rst_n)
            rst_ctr_r <= rst_ctr_r + 16'h1;
    end

    // ─── m68030_top external pins ───────────────────────────────────────
    wire [31:0] ext_a;
    wire [31:0] ext_d_out;
    wire        ext_d_oe;
    wire [31:0] ext_d_in;
    wire        ext_as_n, ext_ds_n, ext_rw;
    wire [2:0]  ext_fc;
    wire [1:0]  ext_siz;
    wire        ext_ecs_n, ext_ocs_n, ext_rstout_n, ext_cbreq_n, ext_bg_n;
    wire        ext_rmc_n, ext_dben_n, ext_ipend_n;
    wire        bus_halted, eu_stop, eu_addr_err, ifu_addr_err;
    wire        status_n, ciout_n;

    // This glue's own responses, driven into m68030_top's input ports.
    wire dsack0_n, dsack1_n, berr_n;

    m68030_top u_cpu (
        .clk_4x        (clk_4x),
        .rst_n         (rst_n),

        .ext_a         (ext_a),
        .ext_d_out     (ext_d_out),
        .ext_d_oe      (ext_d_oe),
        .ext_d_in      (ext_d_in),
        .ext_as_n      (ext_as_n),
        .ext_ds_n      (ext_ds_n),
        .ext_rw        (ext_rw),
        .ext_fc        (ext_fc),
        .ext_siz       (ext_siz),
        .ext_ecs_n     (ext_ecs_n),
        .ext_ocs_n     (ext_ocs_n),
        .ext_rstout_n  (ext_rstout_n),
        .ext_cbreq_n   (ext_cbreq_n),
        .ext_bg_n      (ext_bg_n),
        .ext_rmc_n     (ext_rmc_n),
        .ext_dben_n    (ext_dben_n),
        .ext_ipend_n   (ext_ipend_n),
        .bus_halted    (bus_halted),
        .eu_stop       (eu_stop),
        .eu_addr_err   (eu_addr_err),
        .ifu_addr_err  (ifu_addr_err),

        .dsack0_n      (dsack0_n),
        .dsack1_n      (dsack1_n),
        .sterm_n       (1'b1),        // no synchronous-termination peripheral yet
        .berr_n        (berr_n),
        .halt_n        (1'b1),        // no external HALT source
        .status_n      (status_n),
        .avec_n        (avec_n_w),
        .ipl_n         (3'b111),      // no interrupt sources wired yet
        .br_n          (1'b1),        // no external bus master (no DMA)
        .bgack_n       (1'b1),
        .cback_n       (1'b1),        // no burst-capable memory yet
        .ciin_n        (1'b1),        // cache-inhibit input unused (caches disabled at reset)
        .ciout_n       (ciout_n),
        .cdis_n        (1'b1),        // cache not emulator-disabled
        .mmudis_n      (1'b1)         // MMU not emulator-disabled
    );

    // ─── Autovectoring (plan.md step 7): swap 68000's VPAn for real 68030
    // /AVEC. Every CPU-space (IACK) cycle here autovectors, matching
    // Mackerel-F's own VPAn-tied-low approach — there's no real interrupt
    // controller yet (ipl_n is tied inactive above), so this only matters
    // once an interrupt source exists, but ties it correctly now rather
    // than leaving it undefined.
    wire cpu_space = (ext_fc == 3'b111);
    wire iack      = cpu_space && !ext_as_n;
    wire avec_n_w  = !iack;

    // ─── Memory map ──────────────────────────────────────────────────────
    //   ROM    0x00000000-0x00000FFF   4 KB, on-chip, $readmemh
    //   GPIO   0xFFFFFF00               1 register (write: D[7:0] -> led)
    //   SDCS   0xFFFFFF08               1 register (write: D[0] -> sd_d3/CS#)
    //   UART   0xFFFFFF10-0xFFFFFF17   8 registers (uart16550 register map)
    //   SPI    0xFFFFFF20-0xFFFFFF24   5 registers (tiny_spi register map)
    //   SDRAM  0x02000000-0x03FFFFFF  32 MB, off-chip
    //   (else) unmapped -> BERR via watchdog
    //
    // SDRAM deliberately lives at a high, cleanly-decodable address
    // (bit 25 set, nothing else) rather than the "real" low-address
    // Mackerel-F-style layout (SDRAM at 0, ROM shadowed out after boot) --
    // that shadow-boot trick is a deliberately separate, not-yet-done
    // refinement (plan.md step 4), kept out of scope for this increment
    // so ROM's own ex 0 mapping (already working, already tested through
    // two prior increments) doesn't need touching.
    //
    // Real data-phase gate: for a 68030 write cycle AS asserts at S1 but
    // DS doesn't assert until S3 (data isn't stable until then) -- unlike
    // a plain 68000, so responses are gated on /DS, not /AS, for both
    // reads and writes (reads assert AS+DS together anyway, so this is
    // equivalent there and strictly correct for writes). See MH030's
    // CLAUDE.md S-State Signal Timing section.
    wire cyc_active = !ext_ds_n;

    wire in_rom   = cyc_active && (ext_a[31:12] == 20'h00000);
    wire in_gpio  = cyc_active && (ext_a == 32'hFFFFFF00);
    wire in_sdcs  = cyc_active && (ext_a == 32'hFFFFFF08);
    wire in_uart  = cyc_active && (ext_a[31:8] == 24'hFFFFFF) && (ext_a[7:3] == 5'b00010);
    wire in_spi   = cyc_active && (ext_a[31:8] == 24'hFFFFFF) && (ext_a[7:3] == 5'b00100);
    wire in_sdram = cyc_active && (ext_a[31:25] == 7'b0000001);
    wire in_any   = in_rom || in_gpio || in_sdcs || in_uart || in_spi || in_sdram;

    // DSACK encodings, all confirmed directly against MH030's own
    // rtl/biu_sizing_fsm.sv (next_siz/needs_more), not assumed:
    //   32-bit port (ROM/GPIO/SDCS): dsack0_n=0, dsack1_n=0 (both
    //     asserted) -> port={dsack1_s,dsack0_s}=2'b11, whole request in
    //     one beat, zero added wait states, matching a real on-chip
    //     ROM/register.
    //   16-bit port (SDRAM):    dsack0_n=0, dsack1_n=1 -> port=2'b01.
    //     sdram_done mirrors sdram_adapter's own completion flag directly
    //     -- real wait states here, unlike ROM/GPIO, since SDRAM access
    //     genuinely takes many cycles (activate/CAS-latency/etc).
    //   8-bit port (UART/SPI):  dsack0_n=1, dsack1_n=0 -> port=2'b10.
    //     dsack1_n mirrors the relevant wrapper's own dtack_n directly
    //     (both already do their own internal Wishbone-cycle wait).
    assign dsack0_n = (in_rom || in_gpio || in_sdcs) ? 1'b0 :
                       in_sdram                        ? !sdram_done :
                                                          1'b1;
    assign dsack1_n = (in_rom || in_gpio || in_sdcs) ? 1'b0 :
                       in_uart                          ? uart_dtack_n :
                       in_spi                           ? spi_dtack_n :
                                                          1'b1;

    // ─── ROM: on-chip, longword-indexed. Registered (synchronous) read --
    // deliberately the real BRAM-inferable idiom (single indexed write-
    // never/read-every-cycle, registered output), not a combinational
    // array read, so this maps to a real ECP5 EBR block rather than
    // distributed LUT fabric.
    reg [31:0] rom [0:1023];
    reg [31:0] rom_dout_r;
    initial $readmemh("rom.hex", rom);
    always @(posedge clk_4x)
        rom_dout_r <= rom[ext_a[11:2]];

    // ─── GPIO: single write-only longword register -> 8 LEDs ───────────
    reg [7:0] led_r = 8'h00;
    always @(posedge clk_4x or negedge rst_n) begin
        if (!rst_n)
            led_r <= 8'h00;
        else if (in_gpio && !ext_rw)
            led_r <= ext_d_out[7:0];
    end
    assign led = led_r;

    // ─── SDCS: single write-only register driving the microSD card's own
    // CS# (sd_d3, "sd_d3_csn" per ulx3s_v20.lpf's own comment). tiny_spi
    // has no slave-select output of its own -- software toggles this
    // register directly, matching Mackerel-F's own identical convention
    // (its own `assign cs_spi_sd = ~gpio[6];`). D[0]=1 asserts CS (drives
    // sd_d3 low).
    reg sdcs_r = 1'b0;
    always @(posedge clk_4x or negedge rst_n) begin
        if (!rst_n)
            sdcs_r <= 1'b0;
        else if (in_sdcs && !ext_rw)
            sdcs_r <= ext_d_out[0];
    end
    assign sd_d[3] = !sdcs_r;

    // ─── UART: real OpenCores 16550, via the Mackerel-F-derived wrapper.
    // reg_addr = ext_a[2:0] directly -- the 8 registers are byte-addressed
    // 1:1 within the UART's own window (0x10-0x17), unlike Mackerel-F's
    // own word-strided 16-bit-bus layout, so no shift is needed.
    // biu_byte_lane_ctrl replicates a BYTE write onto all four D[31:0]
    // lanes (confirmed against MH030's own rtl/biu_byte_lane_ctrl.sv), so
    // any fixed 8-bit slice of ext_d_out carries the right value; reads
    // mirror that same replication for symmetry.
    wire       uart_dtack_n;
    wire [7:0] uart_data_out;
    uart u_uart (
        .clk      (clk_4x),
        .rst_n    (rst_n),
        .cs_n     (!in_uart),
        .reg_addr (ext_a[2:0]),
        .rwn      (ext_rw),
        .ds_n     (ext_ds_n),
        .data_in  (ext_d_out[7:0]),
        .data_out (uart_data_out),
        .dtack_n  (uart_dtack_n),
        .irq      (),           // no interrupt controller yet
        .rx       (ftdi_txd),
        .tx       (ftdi_rxd)
    );

    // ─── SPI: real OpenCores tiny_spi, via the Mackerel-F-derived wrapper,
    // for the onboard microSD slot. reg_addr = ext_a[2:0] directly, same
    // byte-addressed-1:1 convention as UART. CS is NOT part of this core
    // (see the sdcs_r register above) -- tiny_spi has no slave-select pin.
    wire       spi_dtack_n;
    wire [7:0] spi_data_out;
    spi u_spi (
        .clk      (clk_4x),
        .rst_n    (rst_n),
        .cs_n     (!in_spi),
        .reg_addr (ext_a[2:0]),
        .rwn      (ext_rw),
        .ds_n     (ext_ds_n),
        .data_in  (ext_d_out[7:0]),
        .data_out (spi_data_out),
        .dtack_n  (spi_dtack_n),
        .irq      (),           // no interrupt controller yet
        .mosi     (sd_cmd),
        .sck      (sd_clk),
        .miso     (sd_d[0])
    );

    // ─── SDRAM: off-chip, via sdram_adapter.v (which wraps the vendored
    // sdram_16bit.v core). Single-word (16-bit) transactions only -- MH030's
    // own dynamic bus sizing (16-bit-port DSACK encoding above) handles all
    // byte/word/longword iteration on the CPU side automatically, so this
    // adapter never needs to know the original request size.
    wire        sdram_done;
    wire [15:0] sdram_rdata;
    sdram_adapter u_sdram (
        .clk        (clk_4x),
        .rst_n      (rst_n),

        .req        (in_sdram),
        .word_addr  (ext_a[24:1]),
        .wr         (!ext_rw),
        .wdata      (ext_d_out[31:16]),  // word write value per
                                          // biu_byte_lane_ctrl's own
                                          // convention (word in [31:16])
        .rdata      (sdram_rdata),
        .done       (sdram_done),

        .sdram_clk  (sdram_clk),
        .sdram_cke  (sdram_cke),
        .sdram_csn  (sdram_csn),
        .sdram_wen  (sdram_wen),
        .sdram_rasn (sdram_rasn),
        .sdram_casn (sdram_casn),
        .sdram_a    (sdram_a),
        .sdram_ba   (sdram_ba),
        .sdram_dqm  (sdram_dqm),
        .sdram_d    (sdram_d)
    );

    // ─── Data bus input mux (CPU read side) ─────────────────────────────
    // SDRAM's 16-bit read value is replicated onto both halves of
    // ext_d_in[31:0], mirroring biu_byte_lane_ctrl's own write-side word
    // replication convention (word in [31:16], repeated onto [15:0]) --
    // the same symmetric-replication approach already used for the UART's
    // own 8-bit reads above.
    assign ext_d_in = in_rom   ? rom_dout_r :
                       in_uart  ? {4{uart_data_out}} :
                       in_spi   ? {4{spi_data_out}} :
                       in_sdram ? {sdram_rdata, sdram_rdata} :
                                  32'h00000000;

    // ─── Bus watchdog: BERR on any access to unmapped space. Mirrors
    // Mackerel-F's own bus_watchdog.v, adapted for DSACK-based
    // termination instead of DTACK. Threshold is generous (64 clk_4x
    // ticks, i.e. many bus cycles' worth) since there is no real timing
    // pressure to be tight here -- only unmapped accesses ever reach it.
    reg [6:0] wd_ctr_r;
    reg       berr_r;
    always @(posedge clk_4x or negedge rst_n) begin
        if (!rst_n) begin
            wd_ctr_r <= 7'h0;
            berr_r   <= 1'b0;
        end else if (ext_as_n) begin
            wd_ctr_r <= 7'h0;
            berr_r   <= 1'b0;
        end else if (in_any) begin
            wd_ctr_r <= 7'h0;
            berr_r   <= 1'b0;
        end else if (wd_ctr_r == 7'd64) begin
            berr_r   <= 1'b1;
        end else begin
            wd_ctr_r <= wd_ctr_r + 7'h1;
        end
    end
    assign berr_n = !berr_r;

endmodule
